packages:
  # Apps is only used in development for testing
  - "apps/*"
  # Packages is used for shared code
  - "packages/*"
  # Adapters holds all the input and output adapters
  - "adapters/*"
  # Frontend holds all the frontend integrations - like react or vue
  - "frontend/*"
  # Backend holds all the backend integrations - like express or fastify
  - "backend/*"
