packages:
  # Packages is used for shared code that is published to npm
  - "packages/*"
  # Adapters holds all the input and output adapters
  - "adapters/*"
  # Frontend holds all the frontend integrations - like react and vue
  - "frontend/*"
  # Backend holds all the backend integrations - like express and fastify
  # along with out test suite - which encapsulates the library as a whole
  - "backend/*"
