name: Publish package to GitHub Packages

on:
  push:
    branches:
      - main
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-gh-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install PNpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
          run_install: false
      
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure .npmrc to use GitHub Packages
        run: |
          cat << EOF > "$HOME/.npmrc"
            @mirasaki-development:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'chore(release): changesets versioning & publication'
          title: 'Changesets: Versioning & Publication'
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}