name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write
      actions: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install PNpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
          run_install: false
      
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Add NPM_TOKEN to .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          title: 'chore: version packages'
          commit: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
      - name: Setup node with GitHub Packages registry
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com

      - name: Use GitHub packages registry in .npmrc
        run: |
          sed -i '$ d' "$HOME/.npmrc"
          cat << EOF > "$HOME/.npmrc"
            @mirasaki-development:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        # if: steps.changesets.outputs.published == 'true'
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send a Discord notification if a publish happens
        if: steps.changesets.outputs.published == 'true' 
        uses: tsickert/discord-webhook@v5.3.0
        continue-on-error: true
        with:
          username: "MD | Release and Publish"
          avatar-url: "https://mirasaki.dev/assets/images/logo.png"
          webhook-url: ${{ secrets.PUBLISH_WEBHOOK_URL_DISCORD }}
          embed-author-name: "@${{ github.repository }}"
          embed-author-url: "https://github.com/${{ github.repository }}"
          embed-author-icon-url: "https://mirasaki.dev/assets/images/projects/icons/imagejs.png"
          embed-color: 14228765
          embed-title: "📦 A new version of ImageJS has been published!"